In [1]:
%cd ..

/home/lab-admin/Code/vr-exoskeleton


/home/lab-admin/Code/vr-exoskeleton/venv/lib/python3.9/site-packages/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


# import

Check that the exported ONNX model and weights have been exported properly.

In [2]:
import onnx
import torch

from vr_exoskeleton import gaze_modeling

In [3]:
model_onnx = onnx.load('best_val_1717450374.onnx')
onnx.checker.check_model(model_onnx)

In [4]:
weights = torch.load('best_val_1717450374.pth')
weights

OrderedDict([('net.0.weight',
              tensor([[-0.0241, -0.0673,  0.0106,  ...,  0.5264,  0.2150, -0.0236],
                      [ 0.0330,  0.0303, -0.1621,  ...,  0.1649, -0.0023, -0.0404],
                      [ 0.1205,  0.0432,  0.0981,  ..., -0.5924, -0.3146, -0.4715],
                      ...,
                      [ 0.1333,  0.0077,  0.2290,  ...,  0.5325,  0.8873,  0.0438],
                      [-0.0157, -0.0950,  0.1908,  ...,  0.6133, -0.3045,  0.5541],
                      [ 0.1204, -0.0772, -0.1595,  ...,  0.3336,  0.3025, -0.2032]],
                     device='cuda:0')),
             ('net.0.bias',
              tensor([ 0.1291, -0.2058,  0.3050, -0.1339, -0.1328, -0.1205,  0.1183, -0.0652,
                       0.1355, -0.1404, -0.1946,  0.0912,  0.0176, -0.1019,  0.0819, -0.0296,
                       0.1241, -0.1750, -0.1320,  0.1131,  0.9038,  0.0280, -0.0594,  0.3429,
                      -0.0396,  0.4580,  0.0411,  0.5736, -0.1479, -0.0190,  0.1680, -0.

In [5]:
model = gaze_modeling.GazeMLP(3)
model.load_state_dict(weights)
model

GazeMLP(
  (net): Sequential(
    (0): Linear(in_features=27, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=3, bias=True)
  )
)

In [6]:
model(torch.zeros(27))

tensor([ 0.0317,  0.0446, -0.0301], grad_fn=<ViewBackward0>)